### PR TITLE
no more intensity limit :cool:

### PR DESCRIPTION
**Pull request by NotSoChill00**

### CODE REVIEW

**Comment by NotSoChill00** [comment]
below gay

**Comment by VerteXGMD** [comment]
You fucking piece of shit, you're nothing, i don't know you! You don't even know Java! How do i know that? Because i feel that you do! You fucking stupid asshole developer! Your pull request is pieca shit

**Comment by NotSoChill00** [comment]
> You fucking piece of shit, you're nothing, i don't know you! You don't even know Java! How do i know that? Because i feel that you do! You fucking stupid asshole developer! Your pull request is pieca shit

you eat shit 
you piss shit
you shit shit

**Comment by NotSoChill00** [comment]
image

**Comment by NotSoChill00** [comment]
image
piece of shit*

**Comment by VerteXGMD** [comment]
image

**Pull request closed without merging**
